interface authenticate-types {
    variant outcome {
        authenticate,
        reject,
        with-context(list<u8>),
    }

    record request {
        uri: string,
        headers: list<tuple<string, list<u8>>>,
    }
}
