package kiwi:kiwi@0.1.0;

world intercept-hook {
    use intercept-types.{context, action};

    export intercept: func(ctx: context) -> action;
}

world authenticate-hook {
    use authenticate-types.{outcome};
    use wasi:http/types@0.2.0-rc-2024-01-16.{incoming-request};

    import wasi:http/outgoing-handler@0.2.0-rc-2024-01-16;

    export authenticate: func(incoming: incoming-request) -> outcome;
}

world internal {
    use wasi:http/types@0.2.0-rc-2024-01-16.{incoming-request};

    import wasi:http/outgoing-handler@0.2.0-rc-2024-01-16;
}
