FROM rust:1.73.0-buster as builder
WORKDIR /app

COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./src ./src

# Install cmake (Required to build librdkafka)
RUN apt-get update && \
    apt-get install -y cmake && \
    apt-get clean

RUN cargo build

COPY . .

ENTRYPOINT ["./bin/entrypoint.sh"]
