FROM rust:1.80-bookworm as builder
WORKDIR /app

# Install cmake (Required to build librdkafka)
RUN apt-get update && \
    apt-get install -y cmake && \
    apt-get clean

COPY . .

RUN cargo build --release --locked --bin kiwi

ENTRYPOINT ["./.circleci/bin/entrypoint.sh"]
