[package]
name = "authenticate-http"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.73.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
kiwi-sdk = { path = "../../src/kiwi-sdk" }

[workspace]
