package kiwi:kiwi@0.1.0;

world intercept-hook {
    use intercept-types.{context, action};

    export intercept: func(ctx: context) -> action;
}

world authenticate-hook {
    use authenticate-types.{request, outcome};

    export authenticate: func(req: request) -> outcome;
}
