version: 2.1

orbs:
  rust: circleci/rust@1.0.0

jobs:
  integration-tests:
    parameters:
      module:
        type: string
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/kiwi
    steps:
      - checkout
      - when:
          condition:
            equal: [<< parameters.module >>, kafka]
          steps:
            - run:
                name: Install Docker Compose
                environment:
                  COMPOSE_VERSION: 'v2.24.7'
                command: |
                  curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
                  chmod +x ~/docker-compose
                  sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - when:
          condition:
            equal: [<< parameters.module >>, kafka]
          steps:
            - run:
                name: Start all services declared in docker-compose.yml
                command: docker-compose up --wait
      - run:
          name: Build Test Docker Image
          command: |
            docker build -t kiwi:latest -f Dockerfile.ci .
      - run:
          name: Run Test
          command: |
            NETWORK_NAME=$(docker network ls --filter name='kiwi' -q)
            [[ -n $NETWORK_NAME ]] && NETWORK_ARG="--network $NETWORK_NAME" || NETWORK_ARG=""
            docker run $NETWORK_ARG \
            --env 'BOOTSTRAP_SERVERS=kafka:19092' \
            --name kiwi-tests \
            kiwi:latest \
            cargo test --test '<< parameters.module >>' -- --nocapture --test-threads=1

workflows:
  integration-tests:
    jobs:
      - integration-tests:
          matrix:
            parameters:
              module:
                - kafka
                - lifecycle
