version: 2.1

orbs:
  rust: circleci/rust@1.0.0

jobs:
  integration-test:
    parameters:
      module:
        type: string
      test:
        type: string
    working_directory: ~/kiwi
    steps:
      - checkout


workflows:
  kafka:
    jobs:
      - integration-test:
          matrix:
            parameters:
              module: ["kafka"]
              test: ["test_kafka_source"]
