version: 2.1

orbs:
  rust: circleci/rust@1.0.0

jobs:
  integration-test:
    parameters:
      module:
        type: string
      test:
        type: string
    docker:
      - image: cimg/rust:1.73.0
      - image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-kafka:latest
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 300000
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    working_directory: ~/repo

    steps:
      - checkout

      # Dependency caching
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.lock" }}

      - run: cargo build

      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.lock" }}
          paths:
            - target

      # Run the test
      - run: cargo test --test '<< parameters.module >>' -- --nocapture --test-threads=1 --test '<< parameters.test >>'

workflows:
  kafka:
    jobs:
      - integration-test:
          matrix:
            parameters:
              module: ["kafka"]
              test: ["test_kafka_source"]
