version: 2.1

orbs:
  rust: circleci/rust@1.0.0

jobs:
  integration-test:
    parameters:
      module:
        type: string
      test:
        type: string
    working_directory: ~/kiwi
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start all services declared in docker-compose.yml
          # TODO: Implement a better way to wait for Kafka to be ready
          command: docker-compose up -d && sleep 10

workflows:
  kafka:
    jobs:
      - integration-test:
          matrix:
            parameters:
              module: ["kafka"]
              test: ["test_kafka_source"]
