name: Bug Report
description: A problem with the existing functionality
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report an issue! 🙏"
  - type: input
    id: version
    attributes:
      label: What version of kiwi are you using?
      placeholder: "If building & running from source, please provide the commit hash. Otherwise, provide the release version."
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "I expected that..."
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run the command '....'
        2. Subscribe to source '....'
        3. Request '...' messages
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Any additional information (e.g. configuration, logs, etc.)"
    validations:
      required: false
