name: Documentation Update
description: Suggest improvements or request additions to the documentation
title: "[Docs] "
labels: ["documentation"]

body:
  - type: markdown
    attributes:
      value: "Help us improve our documentation by submitting a request! 📚"

  - type: input
    id: doc-title
    attributes:
      label: Documentation Title
      description: The title or topic of the documentation page needing improvement or addition.
      placeholder: "Title or topic of the documentation"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Describe the problem with the current documentation or what's missing.
      placeholder: "What issue have you encountered with the current documentation or what is missing?"
    validations:
      required: true

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Detail the improvements or additions you're proposing.
      placeholder: "Please describe the changes you propose..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context that could be helpful.
      placeholder: "Any other context or notes?"
    validations:
      required: false
