[package]
name = "kiwi-sdk"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiwi-macro = { path = "./macro" }
wit-bindgen = "0.16.0"
