interface types {
    // Plugin context
    record context {
        connection: connection-ctx,
        event: event-ctx,
    }

    variant connection-ctx {
        websocket(websocket),
    }

    variant event-ctx {
        kafka(kafka-event-ctx),
    }

    type event-payload = option<list<u8>>;

    record kafka-event-ctx {
        payload: event-payload,
        topic: string,
        timestamp: option<u64>,
        partition: u32,
        offset: u64,
    }

    variant auth {
        jwt(jwt),
    }
    
    record jwt {
        claims: list<tuple<string, string>>,
    }

    record websocket {
        auth: option<auth>,
        addr: option<string>,
    }

    variant action {
        forward,
        discard,
        transform(event-payload),
    }
}
